# Generated by Django 3.1.3 on 2020-12-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='humidity',
            field=models.FloatField(default=0),
        ),
    ]
