# Generated by Django 3.1.3 on 2020-12-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weather_humidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='t_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='t_min',
            field=models.FloatField(default=0),
        ),
    ]
