# Generated by Django 3.1.3 on 2020-12-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_weather_utc_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='precipitation',
            field=models.FloatField(default=0),
        ),
    ]
