# Generated by Django 3.1.3 on 2020-12-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_weather_precipitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='solar_rad',
            field=models.FloatField(default=0),
        ),
    ]
